import {useEffect,useState} from 'react';

type Pair={current:string;candidate:string;transition:string};
type Review={forecast_kind?:string;id:string;expired?:boolean;request:{pairs:Pair[];horizon_s:number;steady_window_s:number;uncertainty_requests:number;current_config:string;candidate_config:string;expected_context:string;max_evidence_age_s:number};decision:{action:string;gain_requests:number|null;break_even_s:number|null;transition_deficit_requests?:number;observed_ready_after_switch_s?:number;observed_transition_complete_after_switch_s?:number;expires_at_unix_s:number;reasons:string[]};pairs:Record<string,unknown>[];limitations:string[];next_step:string;outcomes?:Outcome[]};
type Outcome={id:string;status:string;issues:string[];pairs:{seed:number;observed_net_requests:number;prediction_error_requests:number;observed_payback_after_switch_s:number|null}[];interpretation:string};
type IndependentTest={valid:number;all_offered:number;comparisons:{seed:number;horizon_s:number;action:string;predicted_net:number;measured_switch_minus_keep:number;repayment_s:number|null}[]};
const number=(v:number|null|undefined)=>v==null?'Not established':v.toLocaleString(undefined,{maximumFractionDigits:2});
const titles:Record<string,string>={SWITCH:'Switch — within the measured conditions',WAIT:'Wait — the switch has not earned its cost',KEEP:'Keep the current configuration',INSUFFICIENT_EVIDENCE:'More evidence is needed'};
const explainIssue=(value:string)=>({context_mismatch:'The workload, environment or quality contract differs from the calibration.',homogeneous_calibration_required:'This model was calibrated for one steady workload; the new trace contains changing phases.',calibration_evidence_reused:'Calibration runs cannot also count as independent verification.',evidence_stale_or_future_dated:'The evidence is outside the declared freshness window.',horizon_exceeds_observed_support:'The requested lifetime extends beyond the measured interval.'}[value]||value.replaceAll('_',' '));
async function request<T>(path:string,body?:unknown):Promise<T>{
  const response=await fetch('/api/v1'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-TransitionBench':'1','Idempotency-Key':crypto.randomUUID()},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const data=await response.json();if(!response.ok)throw new Error(data.error?.message||JSON.stringify(data.detail||data));return data;
}
function save(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function DeploymentReview(){
  const [ids,setIds]=useState<string[]>([]),[horizon,setHorizon]=useState(120),[window,setWindow]=useState(30),[allowance,setAllowance]=useState(0);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('Pairing, validity checks and calculations run automatically.');
  const [review,setReview]=useState<Review|null>(null),[sample,setSample]=useState(false);
  const [proof,setProof]=useState<IndependentTest|null>(null);
  useEffect(()=>{fetch('/examples/independent-test/result.json').then(r=>r.ok?r.json():null).then(setProof).catch(()=>setProof(null));},[]);
  function show(value:Review){setReview(value);const url=new URL(location.href);url.searchParams.set('review',value.id);history.replaceState(null,'',url);}
  useEffect(()=>{const id=new URLSearchParams(location.search).get('review');if(!id)return;request<Review>('/proposals/'+encodeURIComponent(id)).then(value=>{show(value);setIds(value.request.pairs.flatMap(p=>[p.current,p.candidate,p.transition]));setHorizon(value.request.horizon_s);setWindow(value.request.steady_window_s);setAllowance(value.request.uncertainty_requests);setSample(value.request.max_evidence_age_s>86400);setMessage('Saved review restored, including outcome history.');}).catch(e=>setError(e.message));},[]);
  async function upload(file:Blob,name:string){const form=new FormData();form.append('file',file,name);const response=await fetch('/api/v1/bundles/import',{method:'POST',headers:{'X-TransitionBench':'1'},body:form});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||JSON.stringify(data));return data.bundle_id as string;}
  async function evaluate(bundleIds=ids,isSample=sample,life=horizon,tail=window,extra=allowance){
    const value=await request<Review>('/proposals/auto',{bundle_ids:bundleIds,horizon_s:life,steady_window_s:tail,uncertainty_requests:extra,max_evidence_age_s:isSample?2592000:86400});
    show(value);setMessage('Evidence paired and checked. Recommendation saved. No deployment executed.');
  }
  async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function importFiles(files:FileList|null,outcome=false){if(!files?.length)return;await run(async()=>{const imported=[];for(const file of Array.from(files)){setMessage(`Checking evidence ${imported.length+1}/${files.length}`);imported.push(await upload(file,file.name));}
    if(outcome&&review){await request(`/proposals/${review.id}/outcomes/imported`,{bundle_ids:imported});show(await request<Review>(`/proposals/${review.id}`));setMessage('New observations linked to the original forecast. Comparison complete.');}
    else{setIds(imported);setSample(false);await evaluate(imported,false);}});}
  async function loadSample(){await run(async()=>{const response=await fetch('/examples/deployment-review/index.json');if(!response.ok)throw new Error('Measured example is not included in this build.');const index=await response.json();const imported=[];
    for(const name of index.files){setMessage(`Checking measured example ${imported.length+1}/${index.files.length}`);const r=await fetch('/examples/deployment-review/'+name);if(!r.ok)throw new Error('Missing example evidence');imported.push(await upload(await r.blob(),name));}
    setIds(imported);setSample(true);setHorizon(120);setWindow(30);setAllowance(0);await evaluate(imported,true,120,30,0);});}
  const outcome=review?.outcomes?.at(-1);
  return <section className="deployment-review">
    <div className="section-heading"><div><h1>Is this configuration change<br/>worth deploying?</h1><p>Compare measured transition costs with cumulative service gains, then check the estimate against later measurements.</p></div></div>
    <div className="review-import"><button className="primary" onClick={loadSample} disabled={busy}>Try the measured GPU case</button><label className="review-upload">Import an evaluation<input type="file" accept=".zip" multiple disabled={busy} onChange={e=>importFiles(e.target.files)}/></label><span>Current + candidate + measured transition · at least three paired seeds · no deployment or GPU calls</span></div>
    <p role="status" className="review-status">{busy?'Working — '+message:message}</p>{error&&<p role="alert" className="error">{error}</p>}
    {ids.length>0&&<div className="review-assumption"><label>How long should the new configuration remain useful? <span>(seconds, assumed)</span><input type="number" min="1" max="3600" value={horizon} onChange={e=>setHorizon(+e.target.value)}/></label><button className="quiet" disabled={busy} onClick={()=>run(()=>evaluate())}>Update recommendation</button></div>}
    {review?<div className="review-card review-result" aria-label="Deployment recommendation"><span className="review-context">{sample?'Historical local GPU case':'Within the imported evidence scope'} · {review.request.current_config} → {review.request.candidate_config}</span><h2>{review.expired?'Review expired — evaluate again':titles[review.decision.action]}</h2>
      <div className="review-metrics"><div><strong>{number(review.decision.gain_requests)}</strong><span>predicted net qualified requests</span></div><div><strong>{number(review.decision.break_even_s)} s</strong><span>{review.forecast_kind==='paired-transition-curve-v1'?'calibration cumulative payback':'legacy model payback estimate'}</span></div><div><strong>{number(review.decision.observed_transition_complete_after_switch_s??review.decision.observed_ready_after_switch_s)} s</strong><span>{review.forecast_kind==='paired-transition-curve-v1'?'declared transition / warmup completion':'legacy declared readiness'}</span></div></div>
      <p>Evaluated lifetime: <strong>{review.request.horizon_s} seconds</strong>. {review.decision.reasons.map(explainIssue).join(' ')}</p><p className="hint">{review.forecast_kind==='paired-transition-curve-v1'?'Advice uses the whole measured transition curve, including downtime and service before warmup completes. Declared completion is a separate milestone, not a gate on already-observed service.':'Saved legacy review: retains the original rate model and readiness gate.'} Predictions assume comparable conditions; this does not observe your production environment.</p>
      <div className="review-actions"><button className="quiet" onClick={()=>save(review,'transitionbench-review-'+review.id+'.json')}>Export evidence-backed review</button><label className="review-upload">Check new outcome evidence<input type="file" accept=".zip" multiple disabled={busy} onChange={e=>importFiles(e.target.files,true)}/></label></div>
      {outcome&&<div className="review-outcome"><h3>{outcome.status==='COMPARABLE'?'Observed result vs prediction':'This outcome does not match the calibrated conditions'}</h3><p>{outcome.issues.map(explainIssue).join(' ')||outcome.interpretation}</p>{outcome.pairs.map(p=><p key={p.seed}>Seed {p.seed}: net {number(p.observed_net_requests)} qualified requests; prediction error {number(p.prediction_error_requests)}; observed repayment {number(p.observed_payback_after_switch_s)} seconds after switch.</p>)}<p className="hint">The original forecast is preserved, including when the result disagrees.</p></div>}
      <details><summary>How this decision was made</summary><p>{review.pairs.length} paired seeds. Maximum observed transition deficit: {number(review.decision.transition_deficit_requests)} qualified requests. Review expires {new Date(review.decision.expires_at_unix_s*1000).toLocaleString()}.</p><ul>{review.limitations.map(x=><li key={x}>{x}</li>)}</ul><p>{review.next_step}</p><pre>{JSON.stringify(review.pairs,null,2)}</pre></details>
    </div>:<div className="review-empty"><h2>A candidate is ready. Should you switch?</h2><p>Start with the recorded GPU case or import matched evaluation bundles. Get a conditional switch or wait recommendation, or a clear explanation of why the evidence is insufficient.</p><p>The review accounts for cumulative qualified service over your chosen lifetime, including the transition. Export its basis, then attach later measurements to check the original estimate. Your serving system decides whether to deploy.</p></div>}
    {proof&&<div className="review-proof" aria-label="Independent validation"><h2>Predicted first. Measured on new seeds.</h2><p>A fixed validation case, separate from the review above. {proof.valid}/9 valid trials · {number(proof.all_offered)} offered requests · RTX 3080 Ti · September 22, 2026.</p><div className="review-proof-scroll"><table><thead><tr><th>Useful lifetime</th><th>Frozen advice</th><th>Predicted net</th><th>Observed net · three seeds</th></tr></thead><tbody>{[20,40,120].map(h=>{const rows=proof.comparisons.filter(p=>p.horizon_s===h);return <tr key={h}><td>{h} s</td><td>{rows[0]?.action}</td><td>{number(rows[0]?.predicted_net)}</td><td>{rows.map(p=>number(p.measured_switch_minus_keep)).join(' / ')}</td></tr>;})}</tbody></table></div><p>Observed cumulative gain first became positive after 30–33 seconds; calibration predicted 34 seconds. Declared warmup ended after 49–52 seconds.</p><p className="hint">Same sustained workload, three observation windows. Keeping A produced zero qualified completions, so this is first positive gain, not recovery from a measured negative balance. Waiting at 20 seconds tied immediate switching. Advice did not beat immediate switching; already running B performed better. APC is an existing vLLM optimization.</p><div className="review-actions"><a href="/examples/independent-test/result.json" download>Inspect all measured results</a><a href="/examples/independent-test/evidence.zip" download>Download reproducible evidence</a></div></div>}
    <details className="review-advanced"><summary>Integration and evaluation settings</summary><p>Automatic HTTP /api/v1/proposals/auto · Python Client.review / Client.observe. Your pipeline can run the same workflow without this page.</p><div className="review-fields"><label>Final steady measurement window (seconds)<input type="number" min="1" max="3600" value={window} onChange={e=>setWindow(+e.target.value)}/></label><label>Additional loss allowance (requests)<input type="number" min="0" value={allowance} onChange={e=>setAllowance(+e.target.value)}/></label></div><p>Defaults: 30-second tail, zero extra loss allowance, at least three paired seeds. These are evaluation assumptions, not a confidence interval. Own-data evidence age: one day; historical example: 30 days.</p>{review&&<p className="hint">Declared context fingerprint: {review.request.expected_context}</p>}</details>
  </section>;
}
